// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: library.proto

package com.example.grpc.service;

public interface BookListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.service.BookListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.example.grpc.service.Book books = 1;</code>
   */
  java.util.List<com.example.grpc.service.Book> 
      getBooksList();
  /**
   * <code>repeated .com.example.grpc.service.Book books = 1;</code>
   */
  com.example.grpc.service.Book getBooks(int index);
  /**
   * <code>repeated .com.example.grpc.service.Book books = 1;</code>
   */
  int getBooksCount();
  /**
   * <code>repeated .com.example.grpc.service.Book books = 1;</code>
   */
  java.util.List<? extends com.example.grpc.service.BookOrBuilder> 
      getBooksOrBuilderList();
  /**
   * <code>repeated .com.example.grpc.service.Book books = 1;</code>
   */
  com.example.grpc.service.BookOrBuilder getBooksOrBuilder(
      int index);
}
