// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: library.proto

package com.example.grpc.service;

public final class Library {
  private Library() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_BookRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_BookRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_BookResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_BookResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_Book_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_Book_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rlibrary.proto\022\007example\"\031\n\013BookRequest\022" +
      "\n\n\002id\030\001 \001(\005\"7\n\014BookResponse\022\n\n\002id\030\001 \001(\005\022" +
      "\033\n\004book\030\002 \001(\0132\r.example.Book\"#\n\004Book\022\014\n\004" +
      "name\030\001 \001(\t\022\r\n\005price\030\002 \001(\0012\255\001\n\016LibrarySer" +
      "vice\0226\n\007getBook\022\024.example.BookRequest\032\025." +
      "example.BookResponse\022/\n\007addBook\022\r.exampl" +
      "e.Book\032\025.example.BookResponse\0222\n\010listBoo" +
      "k\022\r.example.Book\032\025.example.BookResponse0" +
      "\001B\034\n\030com.example.grpc.serviceP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_example_BookRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_example_BookRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_BookRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_example_BookResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_example_BookResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_BookResponse_descriptor,
        new java.lang.String[] { "Id", "Book", });
    internal_static_example_Book_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_example_Book_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_Book_descriptor,
        new java.lang.String[] { "Name", "Price", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
